id: A2F93D92F
title: In Praise of the Three Jewels
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:21:45.514472
  last_modified_at: 2022-03-01 06:21:45.514479
